### ISSUE TITLE
Missing eye-off icon

### ISSUE THREAD

**Issue by oliverkan** [mertefecerit/client-side-vue-datatable#1]
In your video, we see eye-off icons and functionality but when I checked the code there is no related code next the column headers. You might forget to push that changes to your repo :) can you check it please?

**Comment by mertefecerit** [comment]
I forgot to remove the video belongs to an old version. I will share the updated one as soon as possible. Thanks for your feedback. :)

**Comment by ronappleton** [comment]
This is great, but a better doc on how to implement in your application would be great.

I have added to my component via:

import Datatable from '@mertefecerit/vuetable';

![Screenshot 2022-08-18 at 13 06 59](https://user-images.githubusercontent.com/3792420/185390787-655ddf8d-dd02-4b5d-8732-5b4b0518d087.png)
